// <auto-generated />
namespace BETApplicationMVC.Shopify.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initi4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initi4));
        
        string IMigrationMetadata.Id
        {
            get { return "202105201650200_initi4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
